# Generated by Django 6.0.1 on 2026-01-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='reference_id',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='hire_reference',
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
    ]
