"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
from decouple import config as env_config
import os

# --------------------------------------------------
# BASE DIRECTORY
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# SECURITY SETTINGS
# --------------------------------------------------

SECRET_KEY = env_config(
    "DJANGO_SECRET_KEY",
    default="django-insecure-v-^-d0^%#@!)jal=r#$1mo8ps%6#l)e)u8(+1m5#7g&!@wck_$"
)

DEBUG = env_config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = env_config(
    "DJANGO_ALLOWED_HOSTS",
    default="*"
).split(",")

# --------------------------------------------------
# APPLICATION DEFINITION
# --------------------------------------------------

INSTALLED_APPS = [
    # Local apps
    'rentals',

    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # for serving static files on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# --------------------------------------------------
# DATABASE
# --------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': env_config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': env_config('DB_NAME', default='asset_hire_system'),
        'USER': env_config('DB_USER', default='hire_user'),
        'PASSWORD': env_config('DB_PASSWORD', default='Alex@bahati'),
        'HOST': env_config('DB_HOST', default='localhost'),
        'PORT': env_config('DB_PORT', default='5432'),
    }
}

# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# STATIC FILES (PRODUCTION READY)
# --------------------------------------------------

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if DEBUG else []

# WhiteNoise configuration for Render
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --------------------------------------------------
# DEFAULT PRIMARY KEY
# --------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------
# MPESA CONFIG
# --------------------------------------------------

MPESA_CONSUMER_KEY = env_config(
    "MPESA_CONSUMER_KEY",
    default="D09FtPvxJeiXeeFzZVZvRnYzragBgyHlA3DDLQ5vGVlNAyHD"
)

MPESA_CONSUMER_SECRET = env_config(
    "MPESA_CONSUMER_SECRET",
    default="qvmUSsX3HcMmRKBTc9Xgbq6g5apeqcMx6oec63GlkfS7ihnMP3ok5Z3dXSqCU25A"
)

MPESA_PAYBILL = env_config("MPESA_PAYBILL", default="600000")
MPESA_TILL = env_config("MPESA_TILL", default="601234")

# --------------------------------------------------
# SECURITY ENHANCEMENTS FOR PRODUCTION
# --------------------------------------------------

SECURE_SSL_REDIRECT = env_config("DJANGO_SECURE_SSL_REDIRECT", default=True, cast=bool)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
